name: Discord Test

on:
  workflow_dispatch: {}   # permite clicar "Run workflow" no GitHub
  push:
    branches: [ main ]

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Send test message to Discord (via action)
        uses: Ilshidur/action-discord@v2
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK_URL }}
          message: |
            🔔 Teste de alerta do GitHub Actions
            Repositório: ${{ github.repository }}
            Commit: ${{ github.sha }}
            Branch: ${{ github.ref }}

      # Alternativa 100% nativa: cURL (com JSON)
      - name: Send test message to Discord (via curl)
        run: |
          echo '{"content":"🔔 Teste via cURL: workflow ok em '${{ github.repository }}' ('${{ github.ref }}')"}' \
          | tee payload.json
          curl -sS -H "Content-Type: application/json" \
               -d @payload.json \
               "${{ secrets.DISCORD_WEBHOOK_URL }}"
